"""Add timestamp to episode model

Revision ID: 45e5309d9003
Revises: b14e759f94ea
Create Date: 2021-07-27 11:05:42.281654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e5309d9003'
down_revision = 'b14e759f94ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'timestamp')
    # ### end Alembic commands ###
