"""episodes table

Revision ID: 77a959835337
Revises: a369d1681352
Create Date: 2021-07-26 16:09:17.885503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a959835337'
down_revision = 'a369d1681352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('plot', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_plot'), 'episode', ['plot'], unique=False)
    op.create_index(op.f('ix_episode_title'), 'episode', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_title'), table_name='episode')
    op.drop_index(op.f('ix_episode_plot'), table_name='episode')
    op.drop_table('episode')
    # ### end Alembic commands ###
